name: Unit Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.16.0'

      - name: Display Go version
        run: go version

      - name: Run Test
        run: go test -race -count=1 -timeout 30s -coverprofile=coverage.txt -covermode=atomic ./...